let challenge = '30 Days Of JavaScript'
console.log(challenge)
console.log(challenge.length)
console.log(challenge.toUpperCase)
console.log(challenge.toLowerCase)
console.log(challenge.substring(0, 2))
console.log(challenge.substring(0, 10))
console.log(challenge.includes('Script'))
console.log(challenge.split())
console.log(challenge.split(' '))
let string = 'Facebook, Google, Microsoft, Apple, IBM, Oracle, Amazon'
console.log(string.split(' ,'))
console.log(challenge.replace('Javascript', 'Python' ))
console.log(challenge.charAt(15))
console.log(challenge.charCodeAt(J))
console.log(challenge.indexOf('a'))
console.log(challenge.lastIndexOf('a'))
let reason = 'You cannot end a sentence with because because because is a conjunction'
console.log(reason.indexOf('because'))
console.log(reason.lastIndexOf('because'))
console.log(reason.search('because'))
console.log(challenge.trim())
console.log(challenge.startsWith('30'))
console.log(challenge.endsWith('JavaScript'))
console.log(challenge.match('a'))
let word = '30 Days of'
console.log(word.concat('JavaScript'))
console.log(challenge.repeat(2))